from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window5(object):
    def setupUi(self, Window5):
        Window5.setObjectName("Window5")

        Window5.setFixedSize(360, 241)

        Window5.setStyleSheet("QMainWindow { \n"
                              "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,"
                              "stop:0 rgba(196, 42, 3, 255),"
                              "stop:1 rgba(66, 12, 18, 255))\n"
                              "}\n"
                              "QComboBox {\n"
                              "background: #7c1908;\n"
                              "color: #d06814;\n"
                              "border: 1px solid #721507\n"
                              "}\n"
                              "QLabel {\n"
                              "color: #d06814\n"
                              "}\n"
                              "QPushButton {\n"
                              "background: qlineargradient"
                              "(spread:pad, x1:0, y1:0, x2:1, y2:1,"
                              "stop:0 rgba(119, 22, 32, 255),"
                              "stop:1 rgba(140, 30, 2, 255));\n"
                              "border: 1px solid qlineargradient"
                              "(spread:pad, x1:0, y1:0, x2:1, y2:1, "
                              "stop:0 rgba(196, 42, 3, 255), "
                              "stop:1 rgba(66, 12, 18, 255));\n"
                              "color: #d06814;\n"
                              "}\n"
                              "QPushButton:hover {\n"
                              "background: #c42a03;\n"
                              "border: 1px solid qlineargradient"
                              "(spread:pad, x1:0, y1:0, x2:1, y2:1, "
                              "stop:0 rgba(196, 42, 3, 255), "
                              "stop:1 rgba(66, 12, 18, 255));\n"
                              "color: #112d60\n"
                              "}\n"
                              "QPushButton:pressed {\n"
                              "background: #420c12;\n"
                              "border: 1px solid #112d60;\n"
                              "color: #d06814\n"
                              "}")

        self.centralwidget = QtWidgets.QWidget(Window5)
        self.centralwidget.setObjectName("centralwidget")
        self.modeComboBox = QtWidgets.QComboBox(self.centralwidget)

        font = QtGui.QFont()
        font.setFamily("Yandex-UI-Icons-Private")
        font.setPointSize(10)

        self.modeComboBox.setGeometry(QtCore.QRect(220, 70, 121, 20))
        self.modeComboBox.setFont(font)
        self.modeComboBox.setObjectName("modeComboBox")
        self.modeComboBox.addItem("")
        self.modeComboBox.addItem("")

        self.langComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.langComboBox.setGeometry(QtCore.QRect(220, 110, 121, 21))
        self.langComboBox.setFont(font)
        self.langComboBox.setObjectName("langComboBox")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")

        self.filterComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.filterComboBox.setGeometry(QtCore.QRect(220, 190, 121, 20))
        self.filterComboBox.setFont(font)
        self.filterComboBox.setObjectName("filterComboBox")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")

        self.layoutComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.layoutComboBox.setGeometry(QtCore.QRect(220, 150, 121, 20))
        self.layoutComboBox.setFont(font)
        self.layoutComboBox.setObjectName("layoutComboBox")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")

        font = QtGui.QFont()
        font.setFamily("Yandex-UI-Icons-Private")
        font.setPointSize(12)

        self.modeLabel = QtWidgets.QLabel(self.centralwidget)
        self.modeLabel.setGeometry(QtCore.QRect(30, 70, 164, 19))
        self.modeLabel.setFont(font)
        self.modeLabel.setObjectName("modeLabel")

        self.langLabel = QtWidgets.QLabel(self.centralwidget)
        self.langLabel.setGeometry(QtCore.QRect(30, 110, 164, 19))
        self.langLabel.setFont(font)
        self.langLabel.setObjectName("langLabel")

        self.filterLabel = QtWidgets.QLabel(self.centralwidget)
        self.filterLabel.setGeometry(QtCore.QRect(30, 190, 164, 19))
        self.filterLabel.setFont(font)
        self.filterLabel.setObjectName("filterLabel")

        self.layoutLabel = QtWidgets.QLabel(self.centralwidget)
        self.layoutLabel.setGeometry(QtCore.QRect(30, 150, 164, 19))
        self.layoutLabel.setFont(font)
        self.layoutLabel.setObjectName("layoutLabel")

        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.helpButton.setFont(font)
        self.helpButton.setObjectName("helpButton")

        Window5.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Window5)
        self.statusbar.setObjectName("statusbar")
        Window5.setStatusBar(self.statusbar)

        self.retranslateUi(Window5)
        QtCore.QMetaObject.connectSlotsByName(Window5)

    def retranslateUi(self, Window5):
        _translate = QtCore.QCoreApplication.translate
        Window5.setWindowTitle(_translate("Window5", "MainWindow"))
        self.modeComboBox.setItemText(0, _translate("Window5", "Live"))
        self.modeComboBox.setItemText(1, _translate("Window5", "Screenshot"))
        self.modeLabel.setText(_translate("Window5", "Режим распознавания"))
        self.langLabel.setText(_translate("Window5", "Языковой файл"))
        self.langComboBox.setItemText(0, _translate("Window5", "afr"))
        self.langComboBox.setItemText(1, _translate("Window5", "amh"))
        self.langComboBox.setItemText(2, _translate("Window5", "ara"))
        self.langComboBox.setItemText(3, _translate("Window5", "asm"))
        self.langComboBox.setItemText(4, _translate("Window5", "aze"))
        self.langComboBox.setItemText(5, _translate("Window5", "aze_cyrl"))
        self.langComboBox.setItemText(6, _translate("Window5", "bel"))
        self.langComboBox.setItemText(7, _translate("Window5", "ben"))
        self.langComboBox.setItemText(8, _translate("Window5", "bod"))
        self.langComboBox.setItemText(9, _translate("Window5", "bos"))
        self.langComboBox.setItemText(10, _translate("Window5", "bul"))
        self.langComboBox.setItemText(11, _translate("Window5", "cat"))
        self.langComboBox.setItemText(12, _translate("Window5", "ceb"))
        self.langComboBox.setItemText(13, _translate("Window5", "ces"))
        self.langComboBox.setItemText(14, _translate("Window5", "chi_sim"))
        self.langComboBox.setItemText(15, _translate("Window5", "chi_tra"))
        self.langComboBox.setItemText(16, _translate("Window5", "chr"))
        self.langComboBox.setItemText(17, _translate("Window5", "cym"))
        self.langComboBox.setItemText(18, _translate("Window5", "dan"))
        self.langComboBox.setItemText(19, _translate("Window5", "dan_frak"))
        self.langComboBox.setItemText(20, _translate("Window5", "deu"))
        self.langComboBox.setItemText(21, _translate("Window5", "deu_frak"))
        self.langComboBox.setItemText(22, _translate("Window5", "dzo"))
        self.langComboBox.setItemText(23, _translate("Window5", "ell"))
        self.langComboBox.setItemText(24, _translate("Window5", "eng"))
        self.langComboBox.setItemText(25, _translate("Window5", "enm"))
        self.langComboBox.setItemText(26, _translate("Window5", "epo"))
        self.langComboBox.setItemText(27, _translate("Window5", "equ"))
        self.langComboBox.setItemText(28, _translate("Window5", "est"))
        self.langComboBox.setItemText(29, _translate("Window5", "eus"))
        self.langComboBox.setItemText(30, _translate("Window5", "fas"))
        self.langComboBox.setItemText(31, _translate("Window5", "fin"))
        self.langComboBox.setItemText(32, _translate("Window5", "fra"))
        self.langComboBox.setItemText(33, _translate("Window5", "frk"))
        self.langComboBox.setItemText(34, _translate("Window5", "frm"))
        self.langComboBox.setItemText(35, _translate("Window5", "gle"))
        self.langComboBox.setItemText(36, _translate("Window5", "glg"))
        self.langComboBox.setItemText(37, _translate("Window5", "grc"))
        self.langComboBox.setItemText(38, _translate("Window5", "guj"))
        self.langComboBox.setItemText(39, _translate("Window5", "hat"))
        self.langComboBox.setItemText(40, _translate("Window5", "heb"))
        self.langComboBox.setItemText(41, _translate("Window5", "hin"))
        self.langComboBox.setItemText(42, _translate("Window5", "hrv"))
        self.langComboBox.setItemText(43, _translate("Window5", "hun"))
        self.langComboBox.setItemText(44, _translate("Window5", "iku"))
        self.langComboBox.setItemText(45, _translate("Window5", "ind"))
        self.langComboBox.setItemText(46, _translate("Window5", "isl"))
        self.langComboBox.setItemText(47, _translate("Window5", "ita"))
        self.langComboBox.setItemText(48, _translate("Window5", "ita_old"))
        self.langComboBox.setItemText(49, _translate("Window5", "jav"))
        self.langComboBox.setItemText(50, _translate("Window5", "jpn"))
        self.langComboBox.setItemText(51, _translate("Window5", "kan"))
        self.langComboBox.setItemText(52, _translate("Window5", "kat"))
        self.langComboBox.setItemText(53, _translate("Window5", "kat_old"))
        self.langComboBox.setItemText(54, _translate("Window5", "kaz"))
        self.langComboBox.setItemText(55, _translate("Window5", "khm"))
        self.langComboBox.setItemText(56, _translate("Window5", "kir"))
        self.langComboBox.setItemText(57, _translate("Window5", "kor"))
        self.langComboBox.setItemText(58, _translate("Window5", "kur"))
        self.langComboBox.setItemText(59, _translate("Window5", "lao"))
        self.langComboBox.setItemText(60, _translate("Window5", "lat"))
        self.langComboBox.setItemText(61, _translate("Window5", "lav"))
        self.langComboBox.setItemText(62, _translate("Window5", "lit"))
        self.langComboBox.setItemText(63, _translate("Window5", "mal"))
        self.langComboBox.setItemText(64, _translate("Window5", "mar"))
        self.langComboBox.setItemText(65, _translate("Window5", "mkd"))
        self.langComboBox.setItemText(66, _translate("Window5", "mlt"))
        self.langComboBox.setItemText(67, _translate("Window5", "msa"))
        self.langComboBox.setItemText(68, _translate("Window5", "mya"))
        self.langComboBox.setItemText(69, _translate("Window5", "nep"))
        self.langComboBox.setItemText(70, _translate("Window5", "nld"))
        self.langComboBox.setItemText(71, _translate("Window5", "nor"))
        self.langComboBox.setItemText(72, _translate("Window5", "ori"))
        self.langComboBox.setItemText(73, _translate("Window5", "osd"))
        self.langComboBox.setItemText(74, _translate("Window5", "pan"))
        self.langComboBox.setItemText(75, _translate("Window5", "pol"))
        self.langComboBox.setItemText(76, _translate("Window5", "por"))
        self.langComboBox.setItemText(77, _translate("Window5", "pus"))
        self.langComboBox.setItemText(78, _translate("Window5", "ron"))
        self.langComboBox.setItemText(79, _translate("Window5", "rus"))
        self.langComboBox.setItemText(80, _translate("Window5", "san"))
        self.langComboBox.setItemText(81, _translate("Window5", "sin"))
        self.langComboBox.setItemText(82, _translate("Window5", "slk"))
        self.langComboBox.setItemText(83, _translate("Window5", "slk_frak"))
        self.langComboBox.setItemText(84, _translate("Window5", "slv"))
        self.langComboBox.setItemText(85, _translate("Window5", "spa"))
        self.langComboBox.setItemText(86, _translate("Window5", "spa_old"))
        self.langComboBox.setItemText(87, _translate("Window5", "sqi"))
        self.langComboBox.setItemText(88, _translate("Window5", "srp"))
        self.langComboBox.setItemText(89, _translate("Window5", "srp_latn"))
        self.langComboBox.setItemText(90, _translate("Window5", "swa"))
        self.langComboBox.setItemText(91, _translate("Window5", "swe"))
        self.langComboBox.setItemText(92, _translate("Window5", "syr"))
        self.langComboBox.setItemText(93, _translate("Window5", "tam"))
        self.langComboBox.setItemText(94, _translate("Window5", "tel"))
        self.langComboBox.setItemText(95, _translate("Window5", "tgk"))
        self.langComboBox.setItemText(96, _translate("Window5", "tgl"))
        self.langComboBox.setItemText(97, _translate("Window5", "tha"))
        self.langComboBox.setItemText(98, _translate("Window5", "tir"))
        self.langComboBox.setItemText(99, _translate("Window5", "tur"))
        self.langComboBox.setItemText(100, _translate("Window5", "uig"))
        self.langComboBox.setItemText(101, _translate("Window5", "ukr"))
        self.langComboBox.setItemText(102, _translate("Window5", "urd"))
        self.langComboBox.setItemText(103, _translate("Window5", "uzb"))
        self.langComboBox.setItemText(104, _translate("Window5", "uzb_cyrl"))
        self.langComboBox.setItemText(105, _translate("Window5", "vie"))
        self.langComboBox.setItemText(106, _translate("Window5", "yid"))
        self.filterLabel.setText(_translate("Window5", "Фильтрация"))
        self.filterComboBox.setItemText(0, _translate("Window5", "Нет"))
        self.filterComboBox.setItemText(1, _translate("Window5", "Только цифры"))
        self.filterComboBox.setItemText(2, _translate("Window5", "Только символы"))
        self.layoutLabel.setText(_translate("Window5", "Разметка и размер"))
        self.layoutComboBox.setItemText(0, _translate("Window5", "0"))
        self.layoutComboBox.setItemText(1, _translate("Window5", "1"))
        self.layoutComboBox.setItemText(2, _translate("Window5", "2"))
        self.layoutComboBox.setItemText(3, _translate("Window5", "3"))
        self.layoutComboBox.setItemText(4, _translate("Window5", "4"))
        self.layoutComboBox.setItemText(5, _translate("Window5", "5"))
        self.layoutComboBox.setItemText(6, _translate("Window5", "6"))
        self.layoutComboBox.setItemText(7, _translate("Window5", "7"))
        self.layoutComboBox.setItemText(8, _translate("Window5", "8"))
        self.layoutComboBox.setItemText(9, _translate("Window5", "9"))
        self.layoutComboBox.setItemText(10, _translate("Window5", "10"))
        self.layoutComboBox.setItemText(11, _translate("Window5", "11"))
        self.layoutComboBox.setItemText(12, _translate("Window5", "12"))
        self.layoutComboBox.setItemText(13, _translate("Window5", "13"))
        self.helpButton.setText(_translate("Window5", "Помощь"))
